[build]
  command = "pnpm install && pnpm build:admin"
  publish = "apps/admin/out"
  base = "."

[build.environment]
  NODE_VERSION = "18"

# Specify the admin project for dev previews
[dev]
  command = "cd apps/admin && pnpm dev"
  port = 3001
  publish = "apps/admin/.next"
  framework = "#custom"
  targetPort = 3001

# Handle client-side routing for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API routes security
[[headers]]
  for = "/api/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Cache-Control = "no-store, no-cache, must-revalidate"