[build]
  command = "pnpm install && pnpm run build"
  publish = "apps/admin/out"
  base = "."

[build.environment]
  NODE_VERSION = "18"

# Specify which project to use for dev previews
[dev]
  command = "cd apps/admin && pnpm run dev"
  port = 3001
  publish = "apps/admin/.next"
  framework = "#custom"

# Handle client-side routing for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"